kind: Deployment
apiVersion: apps/v1
metadata:
  name: ocm-controller
  namespace: open-cluster-management
  labels:
    app: ocm-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocm-controller
  template:
    metadata:
      labels:
        app: ocm-controller
    spec:
      serviceAccountName: foundation-hub-sa
      containers:
      - name: ocm-controller
        image: ocm-controller
        imagePullPolicy: Always
        args:
          - "/controller"
          - "--enable-agent-deploy=true"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          failureThreshold: 3
          periodSeconds: 10
