kind: Deployment
apiVersion: apps/v1
metadata:
  name: acm-proxyserver
  namespace: open-cluster-management
  labels:
    app: acm-proxyserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acm-proxyserver
  template:
    metadata:
      labels:
        app: acm-proxyserver
    spec:
      serviceAccountName: acm-foundation-sa
      containers:
      - name: acm-proxyserver
        image: acm-proxyserver
        imagePullPolicy: IfNotPresent
        args:
          - "/acm-proxyserver"
          - "--agent-cert-dir=/tmp/agent-cert"
          - "--cert-dir=/tmp/cert"
          - "--secure-port=6443"
        livenessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 6443
          initialDelaySeconds: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            scheme: HTTPS
            port: 6443
          initialDelaySeconds: 2
