resources:
- resources/agent-manifestwork.yaml

namespace: cluster1

images:
- name: klusterlet-addon-workmgr
  newName: quay.io/open-cluster-management/multicloud-manager
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
